import type { Metadata } from "next";
import { Recursive, Roboto } from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";

const recursive = Recursive({ subsets: ['latin'], weight: ["300", "400", "500",] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(recursive.className, "grainy-light")}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
